# @format

services:
  mongodb:
    container_name: ecoponto-arapiraca-backend-db-1
    image: mongo:6
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://${DB_USER}:${DB_PASS}@mongodb:27017/${DB_NAME}?authSource=admin
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  mongo_data:
